source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!


pod 'engine', :git => 'https://theyinvincible@bitbucket.org/cs3217/2016-ps5-pod-a0131465.git', :tag => '0.0.6'

target 'BubbleMania' do

end

target 'BubbleManiaTests' do

end

